
project_id = "pxadbwlidclnfoodjtpd"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "https://fb6c32bb-a043-4a93-994d-054d0c535c01.lovableproject.com"
additional_redirect_urls = ["https://fb6c32bb-a043-4a93-994d-054d0c535c01.lovableproject.com"]
jwt_expiry = 3600
enable_refresh_token_rotation = true

[functions.send-auction-result-email]
verify_jwt = false
