
project_id = "pxadbwlidclnfoodjtpd"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "auth"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-payment-intent]
verify_jwt = true

[functions.stripe-payment-verify]
verify_jwt = true

[functions.stripe-payment-capture]
verify_jwt = true

[functions.stripe-payment-cancel]
verify_jwt = true

[functions.verify-payment-intent]
verify_jwt = true

[functions.update-highest-bid]
verify_jwt = true

[functions.update-dutch-auction-prices]
verify_jwt = false

[functions.get-stripe-publishable-key]
verify_jwt = true

[functions.create-admin-user]
verify_jwt = false

[realtime]
enabled = true
