
project_id = "pxadbwlidclnfoodjtpd"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327

[auth]
enabled = true
port = 54328

[realtime]
enabled = true
port = 54329

[functions.stripe-payment-intent]
verify_jwt = true

[functions.stripe-payment-capture]
verify_jwt = true

[functions.stripe-payment-cancel]
verify_jwt = true

[functions.stripe-payment-verify]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.get-stripe-publishable-key]
verify_jwt = false
